---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
- name: default
  run_list: 
    - "recipe[lifeguard]"
    - "recipe[lifeguard-test]"
  attributes: 
    nodejs:
      install_method: "package"
- name: runit
  run_list: 
    - "recipe[lifeguard]"
    - "recipe[lifeguard-test::runit]"
  attributes: 
    nodejs:
      install_method: "package"
