#!/usr/bin/env node

var http = require("http")

process.title = "lifeguard_test_service"

// Starts a listener on port 9999

var server = http.createServer(function(req,res) {
  res.writeHead(200,{'Content-type': "text/plain"})
  res.end("OK "+process.pid+"\n")
})

server.listen(9999)