#!/usr/bin/env node

var http = require("http")
var port = Number(process.argv[2] || 9999)

process.title = "lifeguard_test_service("+port+")"

// Starts a listener on port 9999

var server = http.createServer(function(req,res) {
  res.writeHead(200,{'Content-type': "text/plain"})
  res.end("OK "+process.pid+"\n")
})

server.listen(port)